# Generated by Django 5.0.1 on 2024-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_situacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='situacao',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Realizado', 'Realizado')], default='Agendado', max_length=10),
        ),
    ]
